//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_PHIEU_GIU_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHO_PHIEU_GIU_HANG()
        {
            this.KHO_CT_PHIEU_GIU_HANG = new HashSet<KHO_CT_PHIEU_GIU_HANG>();
        }
    
        public string SO_PHIEU { get; set; }
        public System.DateTime NGAY_PHIEU { get; set; }
        public Nullable<System.DateTime> NGAY_XUAT_HANG { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MUC_DICH_GIU { get; set; }
        public string HINH_THUC_THANH_TOAN { get; set; }
        public Nullable<bool> XUAT_HOA_DON { get; set; }
        public decimal TONG_TIEN { get; set; }
        public string NGUOI_LAM_PHIEU { get; set; }
        public string TRUC_THUOC { get; set; }
        public Nullable<bool> TRANG_THAI { get; set; }
    
        public virtual CCTC_CONG_TY CCTC_CONG_TY { get; set; }
        public virtual CCTC_NHAN_VIEN CCTC_NHAN_VIEN { get; set; }
        public virtual KH KH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHO_CT_PHIEU_GIU_HANG> KHO_CT_PHIEU_GIU_HANG { get; set; }
    }
}
