//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHO_CT_PHIEU_GIU_HANG
    {
        public int ID { get; set; }
        public string SO_PHIEU { get; set; }
        public string MA_HANG { get; set; }
        public int SL { get; set; }
        public decimal DON_GIA { get; set; }
        public decimal THANH_TIEN { get; set; }
        public string DIA_CHI_XUAT_HANG { get; set; }
        public string GHI_CHU { get; set; }
    
        public virtual HH HH { get; set; }
        public virtual KHO_PHIEU_GIU_HANG KHO_PHIEU_GIU_HANG { get; set; }
    }
}
